version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-devcontainer
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=llama3

volumes:
  ollama-models:
